server {
  listen 80;
  root   /usr/share/nginx/html;
  index  index.html;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Gzip
  gzip on;
  gzip_vary on;
  gzip_min_length 1024;
  gzip_types text/plain text/css text/javascript application/javascript
             application/json application/x-javascript text/xml
             application/xml application/xml+rss text/javascript;

  # Cache static assets aggressively
  location ~* \.(js|css|png|svg|ico|woff2)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
